// lib/mockPlaylists.ts
export const initialPlaylist = [
  {
    id: '1',
    name: 'Lofi Chill',
    description: 'Relax and focus with these lofi beats.',
    coverImage: 'https://i1.sndcdn.com/artworks-000661837984-ax2e2h-t500x500.jpg',
    colors: ['#4c669f', '#3b5998'],
    songs: [
          {
        id: "1",
        title: "Midnight Dreams",
        artist: "Luna Echo",
        album: "Starlight",
        duration: 237,
        liked: false,
        thumbnail : '../assets/images/MSlogo.png',
        uri: "https://www.example.com/audio/midnight-dreams.mp3",
        genre: "Pop",
        releaseYear:"2020",
      },
      {
        id: "2",
        title: "Electric Waves",
        artist: "Neon Pulse",
        album: "Synthwave",
        duration: 198,
        liked: true,
        thumbnail : '../assets/images/MSlogo.png',
        uri: "https://www.example.com/audio/electric-waves.mp3",
        genre: "Pop",
        releaseYear:"2020",
      },
    ],
  },
  {
    id: '2',
    name: 'Workout Energy',
    description: 'Pump up your energy with these high-tempo tracks.',
    coverImage: 'https://i.scdn.co/image/ab67706f000000029bbce1b191f9fa3d46c2b826',
    colors: ['#ff6f61', '#d72638'],
    songs: [
      {
    id: "3",
    title: "Ocean Breeze",
    artist: "Coastal Vibes",
    album: "Summer Days",
    duration: 224,
    liked: false,
    thumbnail : '../assets/images/MSlogo.png',
    uri: "https://www.example.com/audio/ocean-breeze.mp3",
    genre: "Pop",
    releaseYear:"2020",
  },
  {
    id: "4",
    title: "Urban Jungle",
    artist: "City Sounds",
    album: "Metropolis",
    duration: 185,
    liked: true,
    thumbnail : '../assets/images/MSlogo.png',
    uri: "https://www.example.com/audio/urban-jungle.mp3",
    genre: "Pop",
    releaseYear:"2020",
  },
    ],
  },
  {
    id: '3',
    name: 'V-Pop Hits',
    description: 'The hottest V-Pop tracks right now.',
    coverImage: 'https://photo-resize-zmp3.zmdcdn.me/w320_r1x1_webp/cover/5/8/0/f/580fc2f2fefbc6ed7f8b7d3ef528f206.jpg',
    colors: ['#7f00ff', '#e100ff'],
    songs: [
      {
    id: "5",
    title: "Mountain High",
    artist: "Alpine Echoes",
    album: "Nature's Call",
    duration: 246,
    liked: false,
    thumbnail : '../assets/images/MSlogo.png',
    uri: "https://www.example.com/audio/mountain-high.mp3",
    genre: "Pop",
    releaseYear:"2020",
  },
  {
    id: "6",
    title: "Sunset Boulevard",
    artist: "Golden Hour",
    album: "Dusk to Dawn",
    duration: 213,
    liked: false,
    thumbnail : '../assets/images/MSlogo.png',
    uri: "https://www.example.com/audio/sunset-boulevard.mp3",
    genre: "Pop",
    releaseYear:"2020",
  },
    ],
  },
  {
    id: '4',
    name: '90s Love Songs',
    description: 'Romantic classics from the golden 90s.',
    coverImage: 'https://i.scdn.co/image/ab67706c0000da84f78c9f6d4a8ffb5c285ef3d6',
    colors: ['#ff9a9e', '#fad0c4'],
    songs: [
      {
    id:" 7",
    title: "Rainy Day",
    artist: "Ambient Moods",
    album: "Weather Patterns",
    duration: 274,
    liked: true,
    thumbnail : '../assets/images/MSlogo.png',
    uri: "https://www.example.com/audio/rainy-day.mp3",
    genre: "Pop",
    releaseYear:"2020",
  },
  {
    id: "8",
    title: "Neon Lights",
    artist: "City Glow",
    album: "After Hours",
    duration: 192,
    liked: false,
    thumbnail : '../assets/images/MSlogo.png',
    uri: "https://www.example.com/audio/neon-lights.mp3",
    genre: "Pop",
    releaseYear:"2020",
  }
    ],
  },
];
